version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: runner
    volumes:
    - ./src:/opt/app
    ports:
    - 8000:8000
    command: python /opt/app/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
