FROM python:3.7

RUN pip install --upgrade pip

RUN apt-get update
RUN apt-get install -y cron

# cron設定ファイルの移動
ADD python-cron /etc/cron.d/python-cron
RUN chmod 0644 /etc/cron.d/python-cron

ADD ./ /
# init.shにも実行権限の追加
RUN chmod +x /script.sh /init.sh

# CMD cron && touch /etc/cron.d/simple-cron && tail -f /dev/null
CMD /init.sh