# Generated by Django 3.1.4 on 2020-12-10 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weather_data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weather', models.CharField(max_length=20)),
                ('pop', models.IntegerField()),
                ('date_time', models.DateTimeField()),
                ('temp', models.CharField(max_length=200)),
                ('clothing', models.CharField(max_length=20)),
                ('now_rain', models.IntegerField()),
            ],
        ),
    ]
