# Generated by Django 3.1.4 on 2020-12-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather_data',
            name='clothing',
        ),
    ]
