# Generated by Django 3.1.4 on 2021-01-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20210102_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='past_weather_data',
            name='date',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
